# # List of conditions
conditions_list = [
    'vcp=0 and it=2',
    'vcp>0 and it=2',
    'vcp>0 and it=2',
    'vcp=0 and it=2',
    'vcp>0 and it=2 and givt=1',
    'vcp>0 and it=2 and givt=0',
    'vcp=0 and it=2 and givt=1',
    'vcp=0 and it=2 and givt=0',
    'vcp>0 and it=2 and givt=0',
    'vcp=0 and it=2 and givt=1',
    'vcp=0 and it=2 and givt=0',
    'vcp>0 and it=2 and givt=1',
    'vcp>0 and it=2 and givt=0',
    'vcp=0 and it=2 and givt=1',
    'vcp=0 and it=2 and givt=0',
    'vcp>0 and it=2 and givt=1',
    '( vcp>0 and it=2 and givt=0 ) and sivt=1',
    '( vcp>0 and it=2 and givt=0 ) and sivt=0',
    'vcp=0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    '( vcp>0 and it=2 and givt=0 ) and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=1 and sivt=1',
    '( vcp>0 and it=2 and givt=0 ) and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=1 and sivt=1',
    'vcp>0 and it=2 and givt=0',
    'vcp=0 and it=2 and givt=1',
    'vcp=0 and it=2 and givt=0',
    'vcp>0 and it=2 and givt=1',
    'vcp>0 and it=2 and givt=0 and vm=1',
    'vcp=0 and it=2 and givt=1 and vm=0',
    'vcp=0 and it=2 and givt=0 and vm=0',
    'vcp>0 and it=2 and givt=1 and vm=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=FALSE',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp=0 and it=2 and givt=1 and vm=0 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp=0 and it=2 and givt=1 and vm=0 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=1 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=1 and sivt=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=1 then fco = 2000',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=0 then fco < 2000',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=1 then fco = 2000',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=0 then fco < 2000',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=1 then fco = 2000',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=0 then fco < 2000',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=1 then fco = 2000',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and MRC_Viewed=0 then fco < 2000',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp>0 and it=2 and givt=0 and sivt=0',
    'vcp=0 and it=2 and givt=1 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE and q1=1 and q2=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=FALSE and q1=1 and q2=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE and q1=1 and q2=1 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=FALSE and q1=1 and q2=1 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=1 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=0 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0 and q3=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0 and q3=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=1 and q3=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE and q1=1 and q2=1 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=FALSE and q1=1 and q2=1 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=1 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=0 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0 and q3=0 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0 and q3=1 and  q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=0 and  q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=0 and q3=0 and  q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1 and  q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=0 and  q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1 and q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=1 and q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=1 and q3=0 and q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=0 and q3=0 and q4=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=1 and q2=0 and q3=0 and q4=1',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and q1=0 and q2=1 and q3=0 and q4=0',
    '( vcp>0 and it=2 and givt=0 )  and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=1 and sivt=1',
    '( vcp>0 and it=2 and givt=0 )  and sivt=0 and vm=1',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=1',
    'vcp=0 and it=2 and givt=0 and sivt=0 and vm=1',
    'vcp>0 and it=2 and givt=1 and sivt=1 and vm=0',
    '( vcp>0 and it=2 and givt=0 )  and sivt=0 and vm=0',
    '( vcp>0 and it=2 and givt=0 )  and sivt=0 and vm=1  and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    '( vcp>0 and it=2 and givt=0 )  and sivt=0 and vm=1  and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE',
    '( vcp>0 and it=2 and givt=0 )  and sivt=0 and vm=1  and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp=0 and it=2 and givt=0 and sivt=0 and vm=1  and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp=0 and it=2 and givt=0 and sivt=0 and vm=1  and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=1  and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0',
    'vcp=0 and it=2 and givt=1',
    'vcp=0 and it=2 and givt=0',
    'vcp>0 and it=2 and givt=1',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=1 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=0 and sivt=1',
    'vcp=0 and it=2 and givt=0 and sivt=0',
    'vcp>0 and it=2 and givt=1 and sivt=1',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=1',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=0',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=1',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=0',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=0',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=1',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=0',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=1',
    'sivt=0 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'sivt=1 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'sivt=0 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'sivt=1 and vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and sivt=1 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE',
    'vcp>0 and it=2 and givt=0 and sivt=0 and vm=0 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and VIDEO_STARTED>0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE and VIDEO_STARTED>0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=FALSE and VIDEO_STARTED>0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and VIDEO_STARTED>0',
    'vcp=0 and it=2 and givt=1 and vm=0 and VIDEO_STARTED=FALSE AND VIDEO_MRC_VIEWED=TRUE and VIDEO_STARTED>0',
    'vcp=0 and it=2 and givt=1 and vm=0 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and VIDEO_STARTED>0',
    'vcp=0 and it=2 and givt=1 and vm=0 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=TRUE and VIDEO_STARTED=0',
    'vcp>0 and it=2 and givt=0 and vm=1 and VIDEO_STARTED=TRUE AND VIDEO_MRC_VIEWED=FALSE THEN TRUE and VIDEO_STARTED=0']
